# Generated by Django 5.2.3 on 2025-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('actors', models.JSONField(blank=True, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('plot_summary', models.TextField(blank=True, null=True)),
                ('backdrop_path', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
